package T9_Proj;

import java.util.SortedSet;

public class Some_Win extends java.awt.Frame {

    public Some_Win() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        Text_Box = new javax.swing.JTextField();
        Fl_dict = new javax.swing.JCheckBox();
        Read_but = new javax.swing.JButton();
        Text_Field = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Result_area = new javax.swing.JTextArea();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        Text_Box.setText("Name");
        Text_Box.setName("Text_Box"); // NOI18N

        Fl_dict.setText("Html");
        Fl_dict.setName("Fl_dict"); // NOI18N

        Read_but.setText("Read!");
        Read_but.setName("Read_but"); // NOI18N
        Read_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Read_But_Action(evt);
            }
        });

        Text_Field.setText("Text");
        Text_Field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Text_FieldKeyTyped(evt);
            }
        });

        Result_area.setColumns(20);
        Result_area.setRows(5);
        jScrollPane1.setViewportView(Result_area);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Fl_dict, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                    .addComponent(Text_Box))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Read_but))
                            .addComponent(Text_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 280, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Text_Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Read_but))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Fl_dict)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Text_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    Tries tree_link;
    private void Read_But_Action(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Read_But_Action
        // TODO button action
        if (Fl_dict.isSelected()) {
            File_Reader fr = new DReader(Text_Box.getText());
            tree_link = fr.read();
        } else {
            File_Reader fr = new FReader(Text_Box.getText());
            tree_link = fr.read();
        }
    }//GEN-LAST:event_Read_But_Action

    private void Text_FieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Text_FieldKeyTyped
        Tries tr;
        tr = tree_link;
        Sort_Find sort = new Sort_Find();
        if (Text_Field.getText().length() > 2) {
            SortedSet result = sort.Sort(tr.search(Text_Field.getText()));

            Result_area.setText(null);
            Result_area.append(result.toString());

        }
    }//GEN-LAST:event_Text_FieldKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new Some_Win().setVisible(true);
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Fl_dict;
    private javax.swing.JButton Read_but;
    private javax.swing.JTextArea Result_area;
    private javax.swing.JTextField Text_Box;
    private javax.swing.JTextField Text_Field;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
